# Site settings
title: Introduction to programming for geoscientists
name: Gerard Gorman
email: g.gorman@imperial.ac.uk
github_username:  ggorman
twitter_username: gerardjgorman

description: > # this means to ignore newlines until "baseurl:"

  This lecture course has two objectives: learn the basic principles of
  computer programming; become proficient at Python programming as it is
  currently one of the most commonly used languages in computational science.

production_url : http://ggorman.github.io/Introduction-to-programming-for-geoscientist/

# Build settings
markdown: kramdown
