# Site settings
title: Introduction to Python programming for MPECDT

name1: David Ham
address1: Imperial College London
email1: david.ham@imperial.ac.uk
github_username1:  dham

description: > # this means to ignore newlines until "baseurl:"

  The objective of this short course is to ensure that everyone in the
  MPECDT cohort has the core programming skills required to undertake
  basic computational science, and especially the numerical exercises
  in term 1 of the CDT.

baseurl: /Introduction-to-Python-programming-for-MPECDT
production_url : http://dham.github.io/Introduction-to-Python-programming-for-MPECDT

# Build settings
markdown: kramdown
